### PR TITLE
JDK8: java.lang.ClassCastException: com.sun.activation.registries.MailcapFile cannot be cast to jakarta.activation.MailcapRegistry

### LINKED ISSUE #16: change package name to org.eclipse.angus.activation
current implementation uses same package name as the implementation available on SE 8, therefore it would be better to move it to a different package, such as `org.eclipse.angus.activation`; while at this, module name should be updated to `org.eclipse.angus.activation`

### PR DESCRIPTION
**Pull request by jbescos**
Solves:
https://github.com/jakartaee/jaf-api/issues/103
https://github.com/eclipse-ee4j/angus-mail/issues/37

You can verify this PR following the next steps:

1. Checkout this branch and run `$ mvn clean install` . In this way you will have in your local maven repository the version `2.0.0-SNAPSHOT`
2. Checkout this other branch of angus-mail https://github.com/eclipse-ee4j/angus-mail/pull/40 and update the `angus.activation.version` pom.xml property to this version 2.0.0-SNAPSHOT.
3. Configure your JAVA_HOME to a JDK1.8 and run in angus-mail: `mvn clean install -Denforcer.skip`
4. Set the JAVA_HOME to JDK9+ and run `mvn clean install`

### CODE REVIEW

**Comment by lukasj** [comment]
can you rebase this on top of master to resolve conflicts, please?

**Comment by jbescos** [comment]
> can you rebase this on top of master to resolve conflicts, please?

Done

File: activation-registry/src/main/java/org/eclipse/angus/activation/registries/MailcapFile.java [hunk 1]
```diff
@@ -8,7 +8,7 @@
  * SPDX-License-Identifier: BSD-3-Clause
  */
 
-package com.sun.activation.registries;
+package org.eclipse.angus.activation.registries;
```
Comment (lukasj) [inline activation-registry/src/main/java/org/eclipse/angus/activation/registries/MailcapFile.java]: drop `registries` from the package name, it makes no sense to me

File: activation-registry/src/main/java/module-info.java [hunk 2]
```diff
@@ -11,13 +11,13 @@
 /**
  * Eclipse Angus - Activation provides implementation of Jakarta Activation Specification.
  */
-module com.sun.activation.registries {
-    exports com.sun.activation.registries;
+module org.eclipse.angus.activation.registries {
```
Comment (lukasj) [inline activation-registry/src/main/java/module-info.java]: the name should be just `org.eclipse.angus.activation`

File: activation-registry/pom.xml [hunk 3]
```diff
@@ -18,7 +18,7 @@
     <parent>
         <groupId>org.eclipse.angus</groupId>
         <artifactId>angus-activation-project</artifactId>
-        <version>1.1.0-SNAPSHOT</version>
+        <version>2.0.0-SNAPSHOT</version>
```
Comment (lukasj) [inline activation-registry/pom.xml]: version change should and will be done through the extra commit/PR before this change gets merged

File: activation-registry/src/main/java/org/eclipse/angus/activation/registries/MailcapFile.java (hunk 1 above)
Comment (jbescos) [reply activation-registry/src/main/java/org/eclipse/angus/activation/registries/MailcapFile.java:11]: I added it recently because I saw it was there in the last merge I did from master, although I didn't know why was there.

Comment (jbescos) [reply activation-registry/src/main/java/org/eclipse/angus/activation/registries/MailcapFile.java]: I think I was confused with my last merge from master. For some reason I thought registries package was added recently, but it is there from the beginning.

File: activation-registry/pom.xml [hunk 4]
```diff
@@ -2,7 +2,7 @@
 
 <!--
 
-    Copyright (c) 2021, 2022 Oracle and/or its affiliates. All rights reserved.
+    Copyright (c) 2021, 2023 Oracle and/or its affiliates. All rights reserved.
```
Comment (lukasj) [inline activation-registry/pom.xml:5]: there are some updates required in this file around lines 55-67

File: docs/pom.xml [hunk 5]
```diff
@@ -1,7 +1,7 @@
 <?xml version="1.0" encoding="iso-8859-1"?>
 <!--
 
-    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.
+    Copyright (c) 2022, 2023 Oracle and/or its affiliates. All rights reserved.
```
Comment (lukasj) [inline docs/pom.xml:4]: see line ~153

File: activation-registry/pom.xml (hunk 4 above)
Comment (jbescos) [reply activation-registry/pom.xml:5]: Done. To avoid more things like that, after running the next it only finds in the readme, which is expected.
```
angus-activation$ grep -R 'com.sun.activation.registries' ./
./docs/src/main/resources/README.md:Changes module name from `com.sun.activation.registries`
./docs/src/main/resources/README.md:`com.sun.activation.registries` to `org.eclipse.angus.activation`.
```

File: docs/pom.xml (hunk 5 above)
Comment (jbescos) [reply docs/pom.xml:4]: Done

Comment (lukasj) [reply docs/pom.xml:4]: nope :-) - I've said line ~153- the one with: `<group title="Implementation-specific Packages" packages="com.sun.activation*"/>`

**Review by lukasj — APPROVED** [review]
LGTM
